# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

version: '3'

services:
  openpitrix-db:
    image: "mysql:5.6"
    environment:
      - MYSQL_DATABASE=openpitrix
      - MYSQL_ROOT_PASSWORD=password
    ports:
     - "13306:3306" # only for debug
    container_name: "openpitrix-db"

  openpitrix-app:
    build: .
    image: "openpitrix"
    command: app
    links:
      - openpitrix-db:openpitrix-db
    container_name: "openpitrix-app"

  openpitrix-runtime:
    build: .
    image: "openpitrix"
    command: runtime
    links:
      - openpitrix-db:openpitrix-db
    container_name: "openpitrix-runtime"

  openpitrix-cluster:
    build: .
    image: "openpitrix"
    command: cluster
    links:
      - openpitrix-db:openpitrix-db
    container_name: "openpitrix-cluster"

  openpitrix-repo:
    build: .
    image: "openpitrix"
    command: repo
    links:
      - openpitrix-db:openpitrix-db
    container_name: "openpitrix-repo"

  openpitrix-api:
    build: .
    image: "openpitrix"
    command: api
    ports:
     - "9100:9100"
    links:
      - openpitrix-app:openpitrix-app
      - openpitrix-runtime:openpitrix-runtime
      - openpitrix-cluster:openpitrix-cluster
      - openpitrix-repo:openpitrix-repo
    container_name: "openpitrix-api"


