apiVersion: v1
kind: Service
metadata:
  name: openpitrix-task-manager
  namespace: default
  labels:
    app: openpitrix
    service: openpitrix-task-manager
spec:
  selector:
    app: openpitrix
    service: openpitrix-task-manager
  ports:
  - name:  openpitrix-task-manager
    protocol: TCP
    port: 9107
    targetPort: 9107
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-task
  namespace: default
  labels:
    app: openpitrix
spec:
  selector:
    matchLabels:
      app: openpitrix
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        service: openpitrix-task-manager
    spec:
      containers:
      - name: task-manager
        image: openpitrix/openpitrix:latest
        imagePullPolicy: Always
        command:
          - task-manager
        ports:
        - containerPort: 9107
          name: task-manager
        env:
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "task"
        - name: OPENPITRIX_MYSQL_PASSWORD
          value: "password"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi

