apiVersion: v1
kind: Service
metadata:
  name: openpitrix-repo-manager
  namespace: default
  labels:
    app: openpitrix
    service: openpitrix-repo-manager
spec:
  selector:
    app: openpitrix
    service: openpitrix-repo-manager
  ports:
  - name: openpitrix-repo-manager
    protocol: TCP
    port: 9101
    targetPort: 9101
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-repo-manager
  namespace: default
  labels:
    app: openpitrix
spec:
  selector:
    matchLabels:
      app: openpitrix
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        service: openpitrix-repo-manager
    spec:
      containers:
      - name: repo-manager
        image: openpitrix/openpitrix:latest
        imagePullPolicy: Always
        command:
          - repo-manager
        ports:
        - containerPort: 9101
          name: repo-manager
        env:
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "repo"
        - name: OPENPITRIX_MYSQL_PASSWORD
          value: "password"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: openpitrix-repo-indexer
  namespace: default
  labels:
    app: openpitrix
    service: openpitrix-repo-indexer
spec:
  selector:
    app: openpitrix
    service: openpitrix-repo-indexer
  ports:
  - name: openpitrix-repo-indexer
    protocol: TCP
    port: 9108
    targetPort: 9108
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-repo-indexer
  namespace: default
  labels:
    app: openpitrix
spec:
  selector:
    matchLabels:
      app: openpitrix
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        service: openpitrix-repo-indexer
    spec:
      containers:
      - name: repo-indexer
        image: openpitrix/openpitrix:latest
        imagePullPolicy: Always
        command:
          - repo-indexer
        ports:
        - containerPort: 9108
          name: repo-indexer
        env:
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "repo"
        - name: OPENPITRIX_MYSQL_PASSWORD
          value: "password"

        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
