apiVersion: v1
kind: Service
metadata:
  name: openpitrix-api-gateway
  namespace: default
  labels:
    app: openpitrix
    service: api
spec:
  selector:
    app: openpitrix
    service: openpitrix-api-gateway
  ports:
  - name: openpitrix-api-gateway
    protocol: TCP
    port: 9100
    targetPort: 9100
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-api-gateway
  namespace: default
  labels:
    app: openpitrix
spec:
  selector:
    matchLabels:
      app: openpitrix
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        service: openpitrix-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: openpitrix/openpitrix:latest
        imagePullPolicy: Always
        command:
          - api-gateway
        ports:
        - containerPort: 9100
          name: api-gateway
        env:
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "openpitrix"
        - name: OPENPITRIX_MYSQL_PASSWORD
          value: "password"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi

