# +-------------------------------------------------------------------------
# | Copyright (C) 2017 Yunify, Inc.
# +-------------------------------------------------------------------------
# | Licensed under the Apache License, Version 2.0 (the "License");
# | you may not use this work except in compliance with the License.
# | You may obtain a copy of the License in the LICENSE file, or at:
# |
# | http://www.apache.org/licenses/LICENSE-2.0
# |
# | Unless required by applicable law or agreed to in writing, software
# | distributed under the License is distributed on an "AS IS" BASIS,
# | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# | See the License for the specific language governing permissions and
# | limitations under the License.
# +-------------------------------------------------------------------------

swagger: '2.0'

info:
  title: AppHub
  description: >-
    An open platform to package and deploy applications into multiple
    environment such as QingCloud, AWS, Kubernetes etc.
  version: 0.0.1

consumes:
  - application/json
  - application/yaml

produces:
  - application/json
  - application/yaml

schemes:
  - http

# --------------------------------------------------------------------------
# API
# --------------------------------------------------------------------------

basePath: /v1

paths:
  /apps:
    $ref: 'apps.yaml#/apps'
  '/apps/{appId}':
    $ref: 'apps.yaml#/apps-appId'

  /clusters:
    $ref: 'clusters.yaml#/clusters'
  '/clusters/{clusterId}':
    $ref: 'clusters.yaml#/clusters-clusterId'

  /repos:
    $ref: 'repos.yaml#/repos'
  '/repos/{repoId}':
    $ref: 'repos.yaml#/repos-repoId'

  /appruntimes:
    $ref: 'appruntimes.yaml#/appruntimes'
  '/appruntimes/{appRuntimeId}':
    $ref: 'appruntimes.yaml#/appruntimes-appRuntimeId'

# --------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------
