apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  labels:
    app: openpitrix-task-db-ctrl
  name: openpitrix-task-db-ctrl
  namespace: openpitrix-system
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: openpitrix-task-db-ctrl
      name: task-db-ctrl
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.openpitrix-system.svc.cluster.local 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - command: ["flyway", "-X", "-url=jdbc:mysql://openpitrix-db.openpitrix-system.svc.cluster.local/task", "-user=root", "-validateOnMigrate=false", "-locations=filesystem:/flyway/sql/task", "migrate"]
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        image: openpitrix/openpitrix:flyway
        imagePullPolicy: Always
        name: task-db-ctrl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
