# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

swagger: '2.0'

info:
  title: OpenPitrix
  description: >-
    An open platform to package and deploy applications into multiple
    environment such as QingCloud, AWS, Kubernetes etc.
  version: 0.0.1

consumes:
  - application/json
  - application/yaml

produces:
  - application/json
  - application/yaml

schemes:
  - http

basePath: /v1

paths:
  $ref: ./paths/index.yaml

definitions:
  $ref: ./definitions/index.yaml

parameters:
  $ref: ./parameters/index.yaml

responses:
  $ref: ./responses/index.yaml
